[general]
import = [
  "/home/albano/.config/alacritty/default.toml",
]
live_config_reload = true
working_directory = "None"

[colors]
draw_bold_text_with_bright_colors = true

cursor = { text = "CellBackground", cursor = "CellForeground" }

[window]
decorations = "none"
#dynamic_title = true
opacity = 0.75
startup_mode = "Maximized"
padding = { x = 2, y = 2 }
dimensions = { columns = 100, lines = 40 }

[font]
size = 12.0
normal = { family = "CaskaydiaCove Nerd Font", style = "Semilight" }
bold = { family = "CaskaydiaCove Nerd Font", style = "Semibold" }
italic = { family = "CaskaydiaCove Nerd Font", style = "Italic" }


[mouse]
hide_when_typing = true

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = false

#[terminal.shell]
#program = "/usr/bin/bash"
#args = ["-c","tmux new-ses -s al0"]

[terminal]
shell = { program = "/usr/bin/tmux", args = ["new-session", "-s", "al0"] }


