import = ["/home/albano/.config/alacritty/default.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
EDITOR = "nvim"
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Semibold"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Semilight"

[[keyboard.bindings]]
key = "N"
mods = "Command|Shift"

[keyboard.bindings.command]
args = ["new-session", "-d"]
program = "/usr/local/bin/tmux"

[[keyboard.bindings]]
key = "T"
mods = "Command"

[keyboard.bindings.command]
args = ["new-window"]
program = "/usr/local/bin/tmux"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
key = "Q"
mods = "Alt|Shift"

[keyboard.bindings.command]
args = ["kill-window"]
program = "/usr/local/bin/tmux"

[[keyboard.bindings]]
key = "Q"
mods = "Command"

[keyboard.bindings.command]
args = ["kill-pane"]
program = "/usr/local/bin/tmux"

[[keyboard.bindings]]
key = "S"
mods = "Command"

[keyboard.bindings.command]
args = ["split-window", "-h"]
program = "/usr/local/bin/tmux"

[[keyboard.bindings]]
key = "B"
mods = "Command"

[keyboard.bindings.command]
args = ["split-window", "-b"]
program = "/usr/local/bin/tmux"

[[keyboard.bindings]]
key = "Key1"
mods = "Command"

[keyboard.bindings.command]
args = ["selected window", "-t", "1"]
program = "/usr/local/bin/tmux"

[[keyboard.bindings]]
key = "Key2"
mods = "Command"

[keyboard.bindings.command]
args = ["selected window", "-t", "2"]
program = "/usr/local/bin/tmux"

[[keyboard.bindings]]
key = "Key3"
mods = "Command"

[keyboard.bindings.command]
args = ["selected window", "-t", "3"]
program = "/usr/local/bin/tmux"

[[keyboard.bindings]]
key = "Key4"
mods = "Command"

[keyboard.bindings.command]
args = ["selected window", "-t", "4"]
program = "/usr/local/bin/tmux"

[[keyboard.bindings]]
key = "Key5"
mods = "Command"

[keyboard.bindings.command]
args = ["selected window", "-t", "5"]
program = "/usr/local/bin/tmux"

[[keyboard.bindings]]
key = "Key6"
mods = "Command"

[keyboard.bindings.command]
args = ["selected window", "-t", "6"]
program = "/usr/local/bin/tmux"

[[keyboard.bindings]]
key = "Key7"
mods = "Command"

[keyboard.bindings.command]
args = ["selected window", "-t", "7"]
program = "/usr/local/bin/tmux"

[[keyboard.bindings]]
key = "Key8"
mods = "Command"

[keyboard.bindings.command]
args = ["selected window", "-t", "8"]
program = "/usr/local/bin/tmux"

[[keyboard.bindings]]
key = "Key9"
mods = "Command"

[keyboard.bindings.command]
args = ["selected window", "-t", "9"]
program = "/usr/local/bin/tmux"


[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[mouse]
hide_when_typing = true

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
args = ["-c", "tmux new-ses -s al0 /usr/bin/bash --login"]
program = "/usr/bin/bash"

[window]
decorations = "none"
dynamic_title = true
opacity = 0.75
startup_mode = "Maximized"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 100
lines = 40

[window.padding]
x = 2
y = 2
