[general]
import = ["/home/albano/.config/alacritty/default.toml"]
live_config_reload = true
ipc_socket = true
working_directory = "None"

[colors]
draw_bold_text_with_bright_colors = true

[window]
decorations = "none"
#dynamic_title = true
# BEGIN dotfiles terminal-opacity
opacity = 1.0
# END dotfiles terminal-opacity
startup_mode = "Maximized"
padding = { x = 2, y = 2 }
dimensions = { columns = 100, lines = 40 }

# BEGIN dotfiles terminal-font
[font]
size = 12
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaCove Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaCove Nerd Font", style = "Italic" }
# END dotfiles terminal-font


[mouse]
hide_when_typing = true

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = false

[terminal]
shell = { program = "/usr/bin/bash", args = ["--login"] }

#[terminal]
#shell = { program = "/usr/bin/tmux", args = ["new-session"] }
