#!/usr/bin/env bash
# ---------------------------------------------------------------------- #
# Script      : /home/albano/bin/functionsInitBash
# Description : 
# Version     : 0.1
# Author      : Albano Maywitz <allbano@gmail.com> 
# Data        : 19 de janeiro de 2024
# License     : GNU/GPL v3.0 
# ---------------------------------------------------------------------- #
# Use :
# ---------------------------------------------------------------------- #

updateDotfiles() {
    declare -A MSGS
    MSGS["check"]="Verificando dotfiles..."
    MSGS["update"]="Atualizando repositório de dotfiles..."
    echo "${MSGS["check"]}"
    [[ ! -d "$DOTFILES"  ]] && exit 2
    echo "${MSGS["update"]}"
    cd "$DOTFILES" || return
    git pull origin main
    cd "$HOME" || return
}

updateHistory() {
  local LOCALPATH
  LOCALPATH="/home/$USER/github/dotfiles/bash/history"
  local UPTODATE 
  UPTODATE="$(date +'%d/%m/%Y às %H:%M:%S')"
  local HISTNAME
  HISTNAME="$(uname --nodename)-history"
  local UPNAME
  UPNAME="$(uname --nodename)-updates"
  if [ -f "$LOCALPATH/$UPNAME" ]; then
    cp -f "$HOME/.bash_history" "$HOME/github/dotfiles/bash/history/$HISTNAME"
    echo "Seu history foi atualizado em $UPTODATE" >> "$LOCALPATH/$UPNAME"
  else
    touch "$LOCALPATH/$UPNAME"
    cp -f "$HOME/.bash_history" "$HOME/github/dotfiles/bash/history/$HISTNAME"
    echo "Seu history foi atualizado em $UPTODATE" >> "$LOCALPATH/$UPNAME"
  fi 
}

activateVenvPython() {
  local VENVS=("$HOME/.py3env/bin/activate" "$HOME/.py3envpypy/bin/activate")
  "source ${VENVS[$1]}" || exit 2
}

git_current_branch() {\
  if ! git branch --show-current &> /dev/null; then
    echo "Este diretório não é um repositório git!"
  else
    git branch --show-current | xargs -I BRANCH echo -n BRANCH 
  fi
}
