#!/usr/bin/env bash

# ---------------------------------------------------------------------- #
# Script      : /home/albano/bin/functionsInitBash
# Description : 
# Version     : 0.1
# Author      : Albano Maywitz <allbano@gmail.com> 
# Data        : 19 de janeiro de 2024
# License     : GNU/GPL v3.0 
# ---------------------------------------------------------------------- #
# Use :
# ---------------------------------------------------------------------- #
#set -euo pipefail


# launch(): Open the file/URL with the default application.
launch() {
    
    local args="$@"
		xdg-open "$args" && bg

}

# google(): Open google.com in the default browser, arguments are used as search terms.
google() {
	  local terms;
	  terms="$@"
    echo terms
    terms="$(echo -e ${terms// /+})"
	  launch "https://www.google.com/search?q=${terms}" 
}
_exit_status() {
  case $1 in
    0) return ;;
    *) printf '(%d) ' "$1" ;;
  esac
}

ipinf() { 
  if rg -P "(([1-9]\d{0,2})\.){3}(?2)" <<< "$1"; then
	 curl ipinfo.io/"$1"
    else
	  ipawk=$(host "$1" | awk 'NR==1 {print $4}')
	  curl ipinfo.io/${ipawk[1]}
  fi
}

