#!/usr/bin/env bash

# ------------------------------------------------------------------------------- # 
# Script      : updateHistory
# Description : 
# Version     : 0.1
# Author      : Albano Roberto Drescher Von Maywitz 
# Data        : 28 de março de 2024
# ------------------------------------------------------------------------------- # 
# Use : 
# ------------------------------------------------------------------------------- # 
# Copyright (C) 2024, Albano <allbano@gmail.com>.
# License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
# This is free software: you are free to change and redistribute it.
# There is NO WARRANTY, to the extent permitted by law.
# ------------------------------------------------------------------------------- #  

LOCALPATH="/home/$USER/github/dotfiles/bash/history"
UPTODATE="$(date +'%d/%m/%Y às %H:%M:%S')"
HISTNAME="$(uname --nodename)-history"

updateHis() {
    cp -f "$HOME/.bash_history" "$LOCALPATH/$HISTNAME"
    cd "$DOTFILES" || exit 1
    git add "$LOCALPATH/$HISTNAME"
    git commit -m "Your bash_history on PC $(uname --nodename) was updated on $UPTODATE"
    git push origin main 
}

[[ ! -f "$LOCALPATH/$HISTNAME" ]] && touch "$LOCALPATH/$UPNAME"

updateHis


