#!/usr/bin/env bash

# ------------------------------------------------------------------------------- # 
# Script      : usuarios
# Description : Lê os logins e nomes de usuários do siste,a
# Version     : 0.1
# Author      : Albano Roberto Drescher Von Maywitz 
# Data        : 03 de October de 2024
# ------------------------------------------------------------------------------- # 
# Use : 
# ------------------------------------------------------------------------------- # 
# Copyright (C) 2024, Albano <allbano@gmail.com>.
# License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
# This is free software: you are free to change and redistribute it.
# There is NO WARRANTY, to the extent permitted by law.
# ------------------------------------------------------------------------------- #  
#
# Mostra os logins e nomes de usuários do sustema
# Obs.: Lê dados do arquivo /etc/passwd
#
# Versão 1: Mostra os usuários e nomes separados por TAB
# Versão 2: Adiciona suporte à opção -h
# Versão 3: Adicionando suporte à opção -V e opções inválidas
# Versão 4: Arrumado bug quando não tem opções, basename no nome do programa,
#           -V extraindo direto dos cabeçalhos,
#           adicionadas opções --help e --version
# Versão 5: Adicionadas opções -s e --sorte
#
# Albano, Outubro de 2024
# 
# Usando agrupamento de comandos sem formatação

ordenar=0

MENSAGEM_USO="
Uso: $(basename "$(type -p usuarios)") [-h | -v]

  -s, --sorte    Ordena a listagem alfabeticamente
  -h, --help     Mostra esta tela de ajuda e sai
  -v, --version  Mostra a versão do programa e sai
"

# Tratamento das opções de linha de comando
case "$1" in
  -s | --sort)
    ordenar=1
  ;;
  -h | --help)
    echo "${MENSAGEM_USO}"
    exit 0
  ;;
  -v | --version)
    echo -n $(basename $(type -p usuarios))
    grep '^# Versão ' "$0" | tail -1 | cut -d : -f1 | tr -d \#
    exit 0
  ;;
  *)
    if test -n "$1"; then
      echo "Opção Inválida: $1"
      exit 1
    fi
esac


# Processamento
# Extrai listagem
lista=$(cut -d : -f 1,5 /etc/passwd)

# Ordena a listagem (se necessário)
[[ ${ordenar} = 1 ]] && lista=$(echo "$lista" | sort)

# Mostra o resultado para o usuário
echo "$lista" | tr : \\t

#printf "%-30s %s\n" "Login: " "Nome Completo: ";mawk -F: '{printf "%-30s %s\n", $1, $5}' /etc/passwd
