##### STANDARD CONFIG #####

# Add user's local bin directories to PATH
typeset -U PATH path
path=(
  "$HOME/bin"
  "$HOME/.local/bin"
  "$HOME/.cargo/bin"
  "$HOME/.fzf/bin"
  $path
)
# Extra PATH settings
path+=(
  /usr/sbin
  /sbin
)

# Export the updated path
export PATH
