##### STANDARD CONFIG #####

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    export PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    export PATH="$HOME/.local/bin:$PATH"
fi

. "$HOME/.cargo/env"
export PATH="$PATH:/usr/sbin:/sbin"

# set PATH so it includes user's private MODULAR_HOME if it exists
export MODULAR_HOME="$HOME/.modular"
if [ -d "$MODULAR_HOME" ] ; then
    export PATH="$PATH:$MODULAR_HOME:/home/albano/.modular/pkg/packages.modular.com_mojo/bin"
fi

# set PATH so it includes user's private MODULAR_HOME if it exists
export JULIABIN="$HOME/.julia/bin"
if [ -d "$JULIABIN" ] ; then
    export PATH="$PATH:$JULIABIN"
fi

# Load NVM Cli
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Load Angular CLI autocompletion.
source <(ng completion script)

# Init bashrc
[ -f "$HOME/.zshrc" ] &&  . "$HOME/.zshrc"
